### PR TITLE
Fix simulateReadDelay breaking some reads

### PR DESCRIPTION
**Pull request by rodrigok**

### CODE REVIEW

**Comment by jalik** [comment]
Hi @rodrigok, is there really a problem ?
I added conditionnal blocks to test if simulation should be executed but I didn't moved for transformRead() as is should stay in that method and not in the ufs-server (transformRead is called whatever happen).

**Comment by rodrigok** [comment]
Yes, is a problem, if the method sleep is called in the readTransform 50% of my requests never ends.

The problem was solved moving to before the readStream creation.

**Comment by jalik** [comment]
Ok, I moved the read simulation to the place you wanted, but I also moved the write simulation before the transformWrite() call, I guess it's better this way. (now package is version 0.2.7)

**Comment by rodrigok** [comment]
Thanks @jalik, this problem doesn't occurs with you?

**Comment by jalik** [comment]
Nope, haven't noticed it.. are you using UFS in prod ?
I am using it and I don't have problems (for now).

**Comment by rodrigok** [comment]
I'm putting in production today, I had this problem testing local.

Can you accept my another PR https://github.com/jalik/jalik-ufs/pull/12 that solves problems loading audio files from streaming to HTML5 player?

**Pull request closed without merging**
