### PR TITLE
Inform Content Length in file requests

### PR DESCRIPTION
**Pull request by rodrigok**

### CODE REVIEW

**Comment by jalik** [comment]
The first two modifications of your PR were already in the master branch, only the last one is missing, but it's not that easy because transformRead() can change file size so returning file.size() for Content-Length is not that relevant.. we need to return stream length instead.

**Comment by rodrigok** [comment]
Yes, the commits are here because was at my master and as you didn't accepted de PR and changed yourself the commits remains.

About the file length, do you have any idea how to do this, I don't know if is possible to get the streaming size before the stream ends.

Maybe we can pass an object with all headers to transformRead and use the object after to write heads so users can change the object values by reference and remove or change the Content-Length if needed.

**Comment by jalik** [comment]
@rodrigok look that : https://github.com/jalik/jalik-ufs/blob/master/ufs-server.js#L206-L209
The problem is that when I use totalLength, the image is not displayed because size seems not exact when using compression (deflat/gzip), so we have 2 options, first find how to deal with compression and content-length, second just leave it as content-length is optional (giving the wrong length is worst than not giving it).

**Comment by rodrigok** [comment]
Understood. You are right.

Maybe we can set the length only for the response without compression.

My problem is with audio using HTML5 audio player, have you ever tried to upload and load an audio file in a HTML 5 player? The player starts playing the sound and the counter (of elapsed time) goes crazy at the end.

The player before send to server to save (preview):
captura de tela 2015-08-22 as 10 14 49
captura de tela 2015-08-22 as 10 15 04

The player after upload loading audio via stream:
This doesn't happens if response contains the content-length
captura de tela 2015-08-22 as 10 15 16
captura de tela 2015-08-22 as 10 15 29

**Comment by jalik** [comment]
I've spent hours without finding a solution, I can't lose more time as I have work to do, maybe you can see how to add content-length in raw stream : https://github.com/jalik/jalik-ufs/commit/322a98f7199b5af96c30d47348d5062a8129f696

When you uncomment the content-length, an exception is thrown saying cannot render headers after content has been sent, I tried a lot of combination using stream events (finish, end) to be sure to send headers when read stream is ended and then send result of transformRead when ws is finished but it makes the browser loading infinitely..

**Comment by rodrigok** [comment]
Yes, we can't know the size of requests before stream ends.

I saw that all media are requested from browser without accept-encoding header so if we can inform the size of content only in uncompressed streaming and allow transformRead change/remove this header it will solve a lot of problems for us.

**Comment by rodrigok** [comment]
See https://github.com/jalik/jalik-ufs/pull/13

**Pull request closed without merging**
